// Every user-facing string lives here, per locale. `en` defines the shape;
// `es` must match it.

export type Locale = "en" | "es";

const en = {
  appName: "Persona",

  common: {
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    add: "Add",
    edit: "Edit",
    skip: "Add later",
    continue: "Continue",
    makeDefault: "Make default",
    defaultBadge: "Default",
    requiredBadge: "Required",
    sensitiveBadge: "Sensitive",
    optionalBadge: "Optional",
    addAnother: "Add another",
    loading: "Loading…",
    somethingWrong: "Something went wrong. Please try again.",
    notifications: "Notifications",
    dismiss: "Dismiss",
  },

  nav: {
    vault: "My data",
    connections: "Connections",
    settings: "Settings",
    contexts: "Contexts",
    console: "Console",
    logout: "Log out",
  },

  auth: {
    signIn: "Sign in",
    signInLead: "Sign in to choose what you share.",
    firstName: "First name",
    lastName: "Last name",
    email: "Email",
    password: "Password",
    noAccount: "New here? Create your Persona",
    haveAccount: "Already have an account? Sign in",
    otp: {
      title: "Check your email",
      lead: (email: string) => `We sent a 6-digit code to ${email}.`,
      label: "Verification code",
      verify: "Verify",
      expires: "The code is good for 10 minutes.",
      resend: "Send a new code",
      resendIn: (seconds: number) => `Send a new code in ${seconds}s`,
      resent: "A new code is on its way.",
      back: "Use a different email",
    },
    errors: {
      EMAIL_TAKEN: "An account with that email already exists.",
      INVALID_CREDENTIALS: "Invalid email or password.",
      OTP_INVALID: "That code is not right. Check it and try again.",
      OTP_EXPIRED: "That code has expired. Start again to get a new one.",
      OTP_TOO_MANY_ATTEMPTS: "Too many wrong codes. Start again to get a new one.",
      CHALLENGE_NOT_FOUND: "That code is no longer valid. Please start again.",
      OTP_RESEND_TOO_SOON: "Give the first code a moment to arrive.",
      OTP_SEND_LIMIT: "Too many codes sent to that address. Try again later.",
      EMAIL_SEND_FAILED: "We could not send the code. Please try again.",
    } as Record<string, string>,
  },

  landing: {
    title: "Your data lives here",
    body: "You decide what to share and with whom. Persona fills forms for you without handing everything over.",
    points: ["Save your data once", "Share it with one tap", "Never passwords or cards"],
    cta: "Get started",
    signIn: "Sign in",
  },

  onboarding: {
    welcomeNote: "Takes less than 2 minutes",
    essentials: {
      title: "The essentials",
      lead: "Let's start with the basics.",
      emailHint: "We'll use it to identify you. We never share it without your permission.",
    },
    contact: {
      title: "Contact",
      lead: "Your vault grows as you use it. You can skip this and add it later.",
    },
    document: {
      title: "Document",
      lead: "Almost every formal process asks for it. Type it once.",
      hint: "Persona doesn't store photos of your document, only the number you type.",
    },
    health: {
      title: "Health",
      lead: "Useful for appointments and emergencies. Only ever shared with your permission.",
      allergyPlaceholder: "e.g. Penicillin",
    },
    success: {
      title: (name: string) => `All set, ${name}`,
      body: "Your vault is ready. Add more data whenever you want, or when an app asks for it.",
      itemsSaved: (n: number) => `${n} item${n === 1 ? "" : "s"} saved`,
      cta: "Go to my data",
    },
    accountCreated: "Your account is ready",
  },

  vault: {
    title: "My data",
    sections: {
      identity: "Identity",
      document: "Document",
      contact: "Contact",
      location: "Location",
      health: "Health",
    } as Record<string, string>,
    kinds: {
      name: "Name",
      username: "Username",
      avatar: "Avatar",
      birth_date: "Date of birth",
      document: "Document",
      email: "Email",
      phone: "Phone",
      address: "Address",
      blood_type: "Blood type",
      eps: "Health insurer (EPS)",
      allergy: "Allergies",
    } as Record<string, string>,
    nameContexts: {
      legal: "Legal",
      preferred: "Preferred",
      professional: "Professional",
      public: "Public",
    } as Record<string, string>,
    documentFields: { type: "Type", number: "Number", issueDate: "Issued", issuePlace: "Place" },
    phoneFields: { countryCode: "Prefix", number: "Number" },
    addressFields: {
      line1: "Address line 1",
      line2: "Address line 2",
      line3: "Address line 3",
      city: "City",
      postalCode: "ZIP code",
      country: "Country",
    },
    nameContextLabel: "Context",
    label: "Label",
    labelHint: "e.g. Personal, Work",
    emptyGroup: (kind: string) => `No ${kind.toLowerCase()} added yet`,
    usedIn: "used in:",
    deleteConfirm: "Delete this value? Apps it was shared with will stop receiving it.",
    saved: "Saved to your vault",
    deleted: "Value deleted",
    defaultSet: "Now your default",
    errors: {
      SINGLE_VALUE_KIND: "Only one value is allowed here — edit the existing one.",
    } as Record<string, string>,
  },

  contexts: {
    title: "Contexts",
    lead: "What each data group is for.",
    cards: [
      {
        title: "Government & formal",
        body: "Document, full legal name, date of birth. Banks, insurers, registries, contracts.",
      },
      {
        title: "Health",
        body: "Document, health insurer, blood type and allergies. Appointments and emergencies.",
      },
      {
        title: "Shopping & delivery",
        body: "Name, phone, email, shipping address. E-commerce and deliveries.",
      },
      {
        title: "Basic identity",
        body: "Username, email, name. Apps, communities and quick sign-ups.",
      },
    ],
  },

  scopes: {
    name: "Full name",
    given_name: "First name",
    family_name: "Last name",
    username: "Username",
    email: "Email",
    phone: "Phone",
    address: "Address",
    birth_date: "Date of birth",
    document: "Document",
    blood_type: "Blood type",
    eps: "Health insurer (EPS)",
    allergies: "Allergies",
  } as Record<string, string>,

  catalog: {
    documentTypes: {
      CC: "National ID (CC)",
      TI: "Identity card (TI)",
      CE: "Foreigner ID (CE)",
      PASSPORT: "Passport",
      PEP_PPT: "Temporary permit (PEP/PPT)",
    } as Record<string, string>,
    bloodTypes: {
      A_POS: "A+",
      A_NEG: "A−",
      B_POS: "B+",
      B_NEG: "B−",
      AB_POS: "AB+",
      AB_NEG: "AB−",
      O_POS: "O+",
      O_NEG: "O−",
    } as Record<string, string>,
    epsProviders: {
      SURA: "EPS Sura",
      SANITAS: "Sanitas",
      NUEVA_EPS: "Nueva EPS",
      SALUD_TOTAL: "Salud Total",
      COMPENSAR: "Compensar",
      FAMISANAR: "Famisanar",
      COOSALUD: "Coosalud",
      MUTUAL_SER: "Mutual Ser",
    } as Record<string, string>,
    countries: {
      CO: "Colombia",
      AR: "Argentina",
      BR: "Brazil",
      CA: "Canada",
      CL: "Chile",
      EC: "Ecuador",
      ES: "Spain",
      GB: "United Kingdom",
      MX: "Mexico",
      PA: "Panama",
      PE: "Peru",
      US: "United States",
      VE: "Venezuela",
    } as Record<string, string>,
  },

  consent: {
    wantsAccess: "wants to access",
    itemCount: (n: number) => `${n} item${n === 1 ? "" : "s"}`,
    verified: "Verified identity · only what you enable",
    sensitiveDivider: "Sensitive data",
    missingBadge: "Missing from your vault",
    addAndSave: "Add and save to my vault",
    missingNote: "We'll keep it for next time. It's only shared if you approve it here.",
    trivialNote: "Nothing sensitive. This is one click.",
    optionalMissing: "Not in your vault — it won't be shared.",
    confirmTitle: "Share sensitive data?",
    confirmBody: (n: number) =>
      `${n} sensitive item${n === 1 ? "" : "s"} will be shared. You can switch them off before approving.`,
    approve: "Share this data",
    approveMissing: "Complete the missing data to continue",
    dontShare: "Don't share",
    footerNote: "Persona doesn't keep what you don't enable",
    expiredTitle: "Request expired",
    expiredBody: "This request has expired or was already completed. Start again from the app you were using.",
  },

  connections: {
    title: "Connections",
    lead: "What you've shared. You can revoke it any time.",
    itemCount: (n: number) => `${n} item${n === 1 ? "" : "s"}`,
    sharedData: "Shared data",
    revoke: "Revoke access",
    revokeConfirm: (name: string) =>
      `Revoke ${name}'s access? It will stop receiving your data immediately.`,
    revoked: "Access revoked",
    empty: "You're not sharing with anyone yet",
    emptyBody: 'When you use "Sign in with Persona" in an app, you\'ll see here what you shared and can revoke it.',
  },

  settings: {
    title: "Settings",
    privacy: "Privacy",
    confirmSensitive: "Confirm sensitive data",
    notifyAccess: "Notify me of each access",
    updated: "Setting updated",
    downloadData: "Download my data",
    dangerZone: "Danger zone",
    logout: "Log out",
    deleteAccount: "Delete account and vault",
    deleteWarning: "This can't be undone",
    deleteConfirm:
      "Delete your account and everything in your vault? Connected apps lose access immediately. This can't be undone.",
  },
  console: {
    title: "Developer console",
    lead: "Apps that ask for data with \u201cConnect with Persona\u201d.",
    register: "Register an app",
    empty: "No apps yet",
    emptyBody: "Register one to get a client ID and choose what it may ask each person for.",
    emptyHint: "Browse the scope catalogue before you start.",
    appCreated: "App created",
    appDeleted: "App deleted",
    statusOn: "App is active",
    statusOff: "App is paused",
    secretRotated: "New client secret ready",
    scopeCount: (n: number) => `${n} ${n === 1 ? "scope" : "scopes"}`,
    sensitiveCount: (n: number) => `${n} sensitive`,
    status: { active: "Active", disabled: "Paused" },
    back: "My apps",
    purposes: {
      healthcare: "Healthcare",
      employment: "Employment",
      social: "Social",
      retail: "Retail",
      education: "Education",
      government: "Government",
      finance: "Finance",
      other: "Other",
    } as Record<string, string>,

    tabs: { overview: "Overview", scopes: "Scopes", activity: "Activity" },

    form: {
      title: "Register an app",
      lead: "Set out how your app introduces itself and what it will ask for. You can change all of it later.",
      identity: "App identity",
      name: "Name",
      description: "Description",
      descriptionHint: "one line, shown on the consent screen",
      purpose: "Purpose",
      purposeHint:
        "Persona uses the purpose to suggest the right value to each person. Declare healthcare and people are offered their legal name; declare social and they are offered their public one.",
      accent: "Accent colour",
      accentHint: "Used for the monogram, here and on the consent screen.",
      redirect: "Redirect",
      redirectUris: "Redirect URIs",
      addUri: "Add URI",
      removeUri: "Remove",
      create: "Create app",
      cancel: "Cancel",
      createHint: "You will get a client ID and secret when you create it.",
      save: "Save changes",
      saved: "Saved",
    },

    scopes: {
      heading: "Data you will ask for",
      saved: "Scopes updated",
      lead: "Ask only for what your app needs to work. Each person sees this list and can decline the optional ones.",
      catalogLink: "See the scope catalogue",
      optional: "Optional",
      required: "Required",
      sensitive: "Sensitive",
      sensitiveNote:
        "Scopes in amber are sensitive. Asking for them as required lowers the number of people who connect, so ask only when your app genuinely cannot work without them.",
      groups: {
        identity: "Identity",
        contact: "Contact",
        document: "Document",
        health: "Health",
      },
      groupHints: {
        identity: "who the person is",
        contact: "how to reach them",
        document: "official verification",
        health: "only with a health purpose",
      },
      nameNote:
        "You ask for a name, not a version of it. Persona picks the version that fits your purpose and the person can choose another.",
      narrowWarning:
        "Removing a scope disconnects everyone who already approved it. They will be asked again next time they connect.",
      empty: "No scopes selected yet.",
      desc: {
        name: "Full name, in the version that fits your purpose.",
        given_name: "First name only.",
        family_name: "Last name only.",
        username: "The handle they chose in Persona.",
        email: "One email address they pick.",
        phone: "Phone number with country code.",
        address: "Street address, as structured parts plus a formatted line.",
        birth_date: "Date of birth.",
        document: "Identity document: type, number, issue date and place.",
        blood_type: "Blood group.",
        eps: "Health insurer (EPS).",
        allergies: "Declared allergies, as a list.",
      } as Record<string, string>,
    },

    payload: {
      title: "What your app receives",
      lead: "The exact response from the userinfo endpoint, built from your own vault.",
      noData: "no data in the vault",
      alwaysPresent: "always present",
      emptyBody: "Turn on a scope to see the payload.",
    },

    credentials: {
      title: "Credentials",
      clientId: "Client ID",
      clientSecret: "Client secret",
      copy: "Copy",
      copied: "Copied",
      rotate: "Rotate",
      secretHint:
        "Shown in full only when created or rotated. Rotating invalidates the previous secret immediately.",
      revealTitle: "Save this secret now",
      revealBody:
        "This is the only time it is shown. Store it somewhere safe \u2014 if you lose it, rotate for a new one.",
      revealDone: "I have saved it",
      rotateConfirm:
        "Rotate the client secret? The current one stops working immediately and any app still using it will fail to get a token.",
    },

    integration: {
      title: "Integration",
      authorize: "Authorization URL",
      token: "Token exchange",
      userinfo: "Userinfo call",
      authorizeNote:
        "Send the browser here to start consent. Build the query with URLSearchParams so everything is encoded for you.",
      tokenNote:
        "Server-side only. The secret goes in an HTTP Basic header, never in the body and never in the browser.",
      userinfoNote: "Returns only the scopes that person approved. Anything else is absent.",
    },

    settings: {
      title: "Redirects and status",
      active: "App active",
      activeHint: "While paused, nobody can connect and existing tokens stop working.",
      danger: "Delete app",
      dangerBody:
        "Every connection is revoked and the client ID stops working. This can't be undone.",
      delete: "Delete",
      deleteConfirm:
        "Delete this app? Everyone connected to it loses access immediately and the client ID stops working. This can't be undone.",
    },

    activity: {
      title: "Activity",
      lead: "Volume only. You never see who connected or which value they shared.",
      users: "People connected",
      grants: "Grants",
      releases: "Releases",
      revocations: "Revocations",
      recent: "Recent",
      empty: "Nothing yet",
      emptyBody: "Once someone connects, grants and releases show up here.",
      types: { grant: "Granted", release: "Released", revoke: "Revoked" },
    },

    reference: {
      title: "Scope catalogue",
      lead: "Everything Persona can release, what it returns, and an example value.",
      returns: "Returns",
      example: "Example",
      unshareable: "Stored but never shared",
    },
  },
};

export type Strings = typeof en;

const es: Strings = {
  appName: "Persona",

  common: {
    save: "Guardar",
    cancel: "Cancelar",
    delete: "Eliminar",
    add: "Añadir",
    edit: "Editar",
    skip: "Añadir luego",
    continue: "Continuar",
    makeDefault: "Marcar predeterminado",
    defaultBadge: "Predeterminado",
    requiredBadge: "Requerido",
    sensitiveBadge: "Sensible",
    optionalBadge: "Opcional",
    addAnother: "Añadir otra",
    loading: "Cargando…",
    somethingWrong: "Algo salió mal. Inténtalo de nuevo.",
    notifications: "Notificaciones",
    dismiss: "Descartar",
  },

  nav: {
    vault: "Mis datos",
    connections: "Conexiones",
    settings: "Ajustes",
    contexts: "Contextos",
    console: "Consola",
    logout: "Cerrar sesión",
  },

  auth: {
    signIn: "Iniciar sesión",
    signInLead: "Inicia sesión para elegir qué compartes.",
    firstName: "Nombre",
    lastName: "Apellido",
    email: "Correo electrónico",
    password: "Contraseña",
    noAccount: "¿Nuevo aquí? Crea tu Persona",
    haveAccount: "¿Ya tienes cuenta? Inicia sesión",
    otp: {
      title: "Revisa tu correo",
      lead: (email: string) => `Enviamos un código de 6 dígitos a ${email}.`,
      label: "Código de verificación",
      verify: "Verificar",
      expires: "El código sirve durante 10 minutos.",
      resend: "Enviar un código nuevo",
      resendIn: (seconds: number) => `Enviar un código nuevo en ${seconds}s`,
      resent: "Ya va en camino un código nuevo.",
      back: "Usar otro correo",
    },
    errors: {
      EMAIL_TAKEN: "Ya existe una cuenta con ese correo.",
      INVALID_CREDENTIALS: "Correo o contraseña inválidos.",
      OTP_INVALID: "Ese código no es correcto. Revísalo e inténtalo otra vez.",
      OTP_EXPIRED: "Ese código venció. Empieza de nuevo para recibir otro.",
      OTP_TOO_MANY_ATTEMPTS: "Demasiados códigos erróneos. Empieza de nuevo para recibir otro.",
      CHALLENGE_NOT_FOUND: "Ese código ya no sirve. Empieza de nuevo, por favor.",
      OTP_RESEND_TOO_SOON: "Dale un momento al primer código para que llegue.",
      OTP_SEND_LIMIT: "Se enviaron demasiados códigos a ese correo. Inténtalo más tarde.",
      EMAIL_SEND_FAILED: "No pudimos enviar el código. Inténtalo otra vez.",
    },
  },

  landing: {
    title: "Tus datos viven aquí",
    body: "Tú decides qué compartir y con quién. Persona rellena formularios por ti, sin entregar todo.",
    points: ["Guarda tus datos una sola vez", "Compártelos con un toque", "Nunca contraseñas ni tarjetas"],
    cta: "Empezar",
    signIn: "Iniciar sesión",
  },

  onboarding: {
    welcomeNote: "Toma menos de 2 minutos",
    essentials: {
      title: "Lo esencial",
      lead: "Empecemos con lo básico.",
      emailHint: "Lo usaremos para identificarte. Nunca lo compartimos sin tu permiso.",
    },
    contact: {
      title: "Contacto",
      lead: "Tu vault crece con el uso. Puedes saltarte esto y añadirlo luego.",
    },
    document: {
      title: "Documento",
      lead: "Lo piden casi todos los trámites. Lo escribes una vez.",
      hint: "Persona no guarda fotos del documento, solo el número que escribes.",
    },
    health: {
      title: "Salud",
      lead: "Útil para citas y urgencias. Solo se comparte con tu permiso.",
      allergyPlaceholder: "p. ej. Penicilina",
    },
    success: {
      title: (name: string) => `Listo, ${name}`,
      body: "Tu vault está creado. Añade más datos cuando quieras, o cuando una app los pida.",
      itemsSaved: (n: number) => `${n} dato${n === 1 ? "" : "s"} guardado${n === 1 ? "" : "s"}`,
      cta: "Ir a mis datos",
    },
    accountCreated: "Tu cuenta está lista",
  },

  vault: {
    title: "Mis datos",
    sections: {
      identity: "Identidad",
      document: "Documento",
      contact: "Contacto",
      location: "Ubicación",
      health: "Salud",
    },
    kinds: {
      name: "Nombre",
      username: "Nombre de usuario",
      avatar: "Avatar",
      birth_date: "Fecha de nacimiento",
      document: "Documento",
      email: "Correo",
      phone: "Teléfono",
      address: "Dirección",
      blood_type: "Grupo sanguíneo",
      eps: "EPS",
      allergy: "Alergias",
    },
    nameContexts: {
      legal: "Legal",
      preferred: "Preferido",
      professional: "Profesional",
      public: "Público",
    },
    documentFields: { type: "Tipo", number: "Número", issueDate: "Expedición", issuePlace: "Lugar" },
    phoneFields: { countryCode: "Prefijo", number: "Número" },
    addressFields: {
      line1: "Dirección línea 1",
      line2: "Dirección línea 2",
      line3: "Dirección línea 3",
      city: "Ciudad",
      postalCode: "Código postal",
      country: "País",
    },
    nameContextLabel: "Contexto",
    label: "Etiqueta",
    labelHint: "p. ej. Personal, Trabajo",
    emptyGroup: (kind: string) => `Aún no has añadido ${kind.toLowerCase()}`,
    usedIn: "se usa en:",
    deleteConfirm: "¿Eliminar este valor? Las apps con las que se compartió dejarán de recibirlo.",
    saved: "Guardado en tu vault",
    deleted: "Valor eliminado",
    defaultSet: "Ahora es tu predeterminado",
    errors: {
      SINGLE_VALUE_KIND: "Solo se permite un valor aquí — edita el existente.",
    },
  },

  contexts: {
    title: "Contextos",
    lead: "Para qué sirve cada grupo de datos.",
    cards: [
      {
        title: "Trámites y gobierno",
        body: "Documento, nombre legal completo, fecha de nacimiento. Bancos, aseguradoras, registros, contratos.",
      },
      {
        title: "Salud",
        body: "Documento, EPS, grupo sanguíneo y alergias. Citas y urgencias.",
      },
      {
        title: "Compras y envíos",
        body: "Nombre, teléfono, correo, dirección de envío. E-commerce y domicilios.",
      },
      {
        title: "Identidad básica",
        body: "Nombre de usuario, correo, nombre. Apps, comunidades y registro exprés.",
      },
    ],
  },

  scopes: {
    name: "Nombre completo",
    given_name: "Nombre",
    family_name: "Apellido",
    username: "Nombre de usuario",
    email: "Correo",
    phone: "Teléfono",
    address: "Dirección",
    birth_date: "Fecha de nacimiento",
    document: "Documento",
    blood_type: "Grupo sanguíneo",
    eps: "EPS",
    allergies: "Alergias",
  },

  catalog: {
    documentTypes: {
      CC: "Cédula de ciudadanía (CC)",
      TI: "Tarjeta de identidad (TI)",
      CE: "Cédula de extranjería (CE)",
      PASSPORT: "Pasaporte",
      PEP_PPT: "Permiso temporal (PEP/PPT)",
    },
    bloodTypes: {
      A_POS: "A+",
      A_NEG: "A−",
      B_POS: "B+",
      B_NEG: "B−",
      AB_POS: "AB+",
      AB_NEG: "AB−",
      O_POS: "O+",
      O_NEG: "O−",
    },
    epsProviders: {
      SURA: "EPS Sura",
      SANITAS: "Sanitas",
      NUEVA_EPS: "Nueva EPS",
      SALUD_TOTAL: "Salud Total",
      COMPENSAR: "Compensar",
      FAMISANAR: "Famisanar",
      COOSALUD: "Coosalud",
      MUTUAL_SER: "Mutual Ser",
    },
    countries: {
      CO: "Colombia",
      AR: "Argentina",
      BR: "Brasil",
      CA: "Canadá",
      CL: "Chile",
      EC: "Ecuador",
      ES: "España",
      GB: "Reino Unido",
      MX: "México",
      PA: "Panamá",
      PE: "Perú",
      US: "Estados Unidos",
      VE: "Venezuela",
    },
  },

  consent: {
    wantsAccess: "quiere acceder a",
    itemCount: (n: number) => `${n} dato${n === 1 ? "" : "s"}`,
    verified: "Identidad verificada · solo lo que actives",
    sensitiveDivider: "Datos sensibles",
    missingBadge: "Falta en tu vault",
    addAndSave: "Añadir y guardar en mi vault",
    missingNote: "La guardamos para la próxima vez. Solo se comparte si lo apruebas aquí.",
    trivialNote: "Nada sensible. Esto es de un clic.",
    optionalMissing: "No está en tu vault — no se compartirá.",
    confirmTitle: "¿Compartir datos sensibles?",
    confirmBody: (n: number) =>
      n === 1
        ? "Se compartirá 1 dato sensible. Puedes desactivarlo antes de aprobar."
        : `Se compartirán ${n} datos sensibles. Puedes desactivarlos antes de aprobar.`,
    approve: "Compartir estos datos",
    approveMissing: "Completa los datos faltantes para continuar",
    dontShare: "No compartir",
    footerNote: "Persona no guarda lo que no actives",
    expiredTitle: "Solicitud expirada",
    expiredBody: "Esta solicitud expiró o ya se completó. Empieza de nuevo desde la app que estabas usando.",
  },

  connections: {
    title: "Conexiones",
    lead: "Lo que compartiste. Puedes revocarlo cuando quieras.",
    itemCount: (n: number) => `${n} dato${n === 1 ? "" : "s"}`,
    sharedData: "Datos compartidos",
    revoke: "Revocar acceso",
    revokeConfirm: (name: string) =>
      `¿Revocar el acceso de ${name}? Dejará de recibir tus datos de inmediato.`,
    revoked: "Acceso revocado",
    empty: "Aún no compartes con nadie",
    emptyBody: 'Cuando uses "Ingresar con Persona" en una app, verás aquí qué compartiste y podrás revocarlo.',
  },

  settings: {
    title: "Ajustes",
    privacy: "Privacidad",
    confirmSensitive: "Confirmar datos sensibles",
    notifyAccess: "Avisarme de cada acceso",
    updated: "Ajuste actualizado",
    downloadData: "Descargar mis datos",
    dangerZone: "Zona de riesgo",
    logout: "Cerrar sesión",
    deleteAccount: "Eliminar cuenta y vault",
    deleteWarning: "No se puede deshacer",
    deleteConfirm:
      "¿Eliminar tu cuenta y todo tu vault? Las apps conectadas pierden acceso de inmediato. No se puede deshacer.",
  },
  console: {
    title: "Consola de desarrollador",
    lead: "Aplicaciones que piden datos con \u00abConectar con Persona\u00bb.",
    register: "Registrar app",
    empty: "A\u00fan no tienes apps",
    emptyBody:
      "Registra una para obtener un client ID y elegir qu\u00e9 puede pedirle a cada persona.",
    emptyHint: "Revisa el cat\u00e1logo de scopes antes de empezar.",
    appCreated: "App creada",
    appDeleted: "App eliminada",
    statusOn: "La app está activa",
    statusOff: "La app está en pausa",
    secretRotated: "Nuevo client secret listo",
    scopeCount: (n: number) => `${n} scope${n === 1 ? "" : "s"}`,
    sensitiveCount: (n: number) => `${n} sensible${n === 1 ? "" : "s"}`,
    status: { active: "Activa", disabled: "En pausa" },
    back: "Mis apps",
    purposes: {
      healthcare: "Salud",
      employment: "Empleo",
      social: "Social",
      retail: "Comercio",
      education: "Educaci\u00f3n",
      government: "Gobierno",
      finance: "Finanzas",
      other: "Otro",
    },

    tabs: { overview: "Resumen", scopes: "Scopes", activity: "Actividad" },

    form: {
      title: "Registrar una app",
      lead: "Define c\u00f3mo se presenta tu app y qu\u00e9 datos pedir\u00e1. Puedes cambiarlo todo despu\u00e9s.",
      identity: "Identidad de la app",
      name: "Nombre",
      description: "Descripci\u00f3n",
      descriptionHint: "una l\u00ednea, visible en el consentimiento",
      purpose: "Prop\u00f3sito",
      purposeHint:
        "Persona usa el prop\u00f3sito para sugerir el valor correcto a cada persona. Con salud se ofrece el nombre legal; con social, el p\u00fablico.",
      accent: "Color de acento",
      accentHint: "Se usa en el monograma, aqu\u00ed y en la pantalla de consentimiento.",
      redirect: "Redirecci\u00f3n",
      redirectUris: "URIs de redirecci\u00f3n",
      addUri: "A\u00f1adir URI",
      removeUri: "Quitar",
      create: "Crear app",
      cancel: "Cancelar",
      createHint: "Obtendr\u00e1s client ID y secret al crearla.",
      save: "Guardar cambios",
      saved: "Guardado",
    },

    scopes: {
      heading: "Datos que pedir\u00e1s",
      saved: "Scopes actualizados",
      lead: "Pide solo lo que tu app necesita para funcionar. Cada persona ver\u00e1 esta lista y podr\u00e1 declinar los opcionales.",
      catalogLink: "Ver cat\u00e1logo de scopes",
      optional: "Opcional",
      required: "Obligatorio",
      sensitive: "Sensible",
      sensitiveNote:
        "Los scopes en \u00e1mbar son sensibles. Pedirlos como obligatorios reduce cu\u00e1nta gente conecta, as\u00ed que p\u00eddelos solo si tu app de verdad no funciona sin ellos.",
      groups: {
        identity: "Identidad",
        contact: "Contacto",
        document: "Documento",
        health: "Salud",
      },
      groupHints: {
        identity: "qui\u00e9n es la persona",
        contact: "c\u00f3mo llegar a ella",
        document: "verificaci\u00f3n oficial",
        health: "solo con prop\u00f3sito sanitario",
      },
      nameNote:
        "Pides un nombre, no una versi\u00f3n concreta. Persona elige la que encaja con tu prop\u00f3sito y la persona puede cambiarla.",
      narrowWarning:
        "Quitar un scope desconecta a quienes ya lo aprobaron. Se les preguntar\u00e1 de nuevo la pr\u00f3xima vez que conecten.",
      empty: "A\u00fan no has elegido scopes.",
      desc: {
        name: "Nombre completo, en la versi\u00f3n que encaja con tu prop\u00f3sito.",
        given_name: "Solo el nombre.",
        family_name: "Solo los apellidos.",
        username: "El usuario que eligi\u00f3 en Persona.",
        email: "Un correo que la persona elija.",
        phone: "Tel\u00e9fono con indicativo de pa\u00eds.",
        address: "Direcci\u00f3n en partes estructuradas m\u00e1s una l\u00ednea formateada.",
        birth_date: "Fecha de nacimiento.",
        document: "Documento de identidad: tipo, n\u00famero, fecha y lugar de expedici\u00f3n.",
        blood_type: "Grupo sangu\u00edneo.",
        eps: "EPS o aseguradora de salud.",
        allergies: "Alergias declaradas, como lista.",
      },
    },

    payload: {
      title: "Lo que recibe tu app",
      lead: "La respuesta exacta del endpoint userinfo, construida con tu propio vault.",
      noData: "sin dato en el vault",
      alwaysPresent: "siempre presente",
      emptyBody: "Activa un scope para ver el payload.",
    },

    credentials: {
      title: "Credenciales",
      clientId: "Client ID",
      clientSecret: "Client secret",
      copy: "Copiar",
      copied: "Copiado",
      rotate: "Rotar",
      secretHint:
        "Solo se muestra completo al crearlo o al rotarlo. Rotar invalida el anterior de inmediato.",
      revealTitle: "Guarda este secret ahora",
      revealBody:
        "Es la \u00fanica vez que se muestra. Gu\u00e1rdalo en un sitio seguro \u2014 si lo pierdes, rota para obtener otro.",
      revealDone: "Ya lo guard\u00e9",
      rotateConfirm:
        "\u00bfRotar el client secret? El actual deja de funcionar de inmediato y cualquier app que lo use fallar\u00e1 al pedir el token.",
    },

    integration: {
      title: "Integraci\u00f3n",
      authorize: "URL de autorizaci\u00f3n",
      token: "Intercambio de token",
      userinfo: "Llamada a userinfo",
      authorizeNote:
        "Env\u00eda el navegador aqu\u00ed para iniciar el consentimiento. Construye la query con URLSearchParams y todo queda codificado.",
      tokenNote:
        "Solo desde tu servidor. El secret va en una cabecera HTTP Basic, nunca en el cuerpo ni en el navegador.",
      userinfoNote: "Devuelve solo los scopes que esa persona aprob\u00f3. El resto no aparece.",
    },

    settings: {
      title: "Redirecciones y estado",
      active: "App activa",
      activeHint: "En pausa, nadie puede conectar y los tokens existentes dejan de funcionar.",
      danger: "Eliminar app",
      dangerBody:
        "Se revocan todas las conexiones y el client ID deja de funcionar. No se puede deshacer.",
      delete: "Eliminar",
      deleteConfirm:
        "\u00bfEliminar esta app? Todas las personas conectadas pierden acceso de inmediato y el client ID deja de funcionar. No se puede deshacer.",
    },

    activity: {
      title: "Actividad",
      lead: "Solo volumen. Nunca ves qui\u00e9n conect\u00f3 ni qu\u00e9 valor comparti\u00f3.",
      users: "Personas conectadas",
      grants: "Concesiones",
      releases: "Entregas",
      revocations: "Revocaciones",
      recent: "Reciente",
      empty: "A\u00fan no hay nada",
      emptyBody: "Cuando alguien conecte, las concesiones y entregas aparecer\u00e1n aqu\u00ed.",
      types: { grant: "Concedido", release: "Entregado", revoke: "Revocado" },
    },

    reference: {
      title: "Cat\u00e1logo de scopes",
      lead: "Todo lo que Persona puede entregar, qu\u00e9 devuelve y un valor de ejemplo.",
      returns: "Devuelve",
      example: "Ejemplo",
      unshareable: "Se guarda pero nunca se comparte",
    },
  },
};

const STRINGS: Record<Locale, Strings> = { en, es };

export function getStrings(locale?: string): Strings {
  return STRINGS[locale === "es" ? "es" : "en"];
}
