import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { chromium, type BrowserContext } from "playwright-core";

// Measures the second pre-registered threshold: how long the consent screen
// takes to become usable. The clock starts where a person's click starts, at
// the authorize endpoint, and stops when the approve button is present and
// enabled — that is, when the decision can actually be made.
const WEB = process.env.PERF_WEB_URL ?? "http://localhost:4420";
const API = process.env.PERF_API_URL ?? "http://localhost:4400";
const RUNS = Number(process.env.PERF_RUNS ?? 10);
const APPROVE = "Share this data";

const CLIENT_ID = "clinic";
const REDIRECT_URI = "http://localhost:4411/callback";
const SCOPE = "openid name email phone address birth_date document blood_type eps allergies";

// A normal demo vault, and the 1,000-item vault the API benchmark uses, so the
// two rows show whether vault size reaches the interface.
const SUBJECTS = [
  { email: "camila@example.com", label: "demo vault (15 items)" },
  { email: "perf@example.com", label: "large vault (1,000 items)" },
];

type Sample = { label: string; email: string; times: number[] };

// Signs in through the development-only endpoint, so no password is handled.
async function sessionCookies(email: string): Promise<{ name: string; value: string }[]> {
  const jar: { name: string; value: string }[] = [];
  const collect = (res: Response): void => {
    for (const raw of res.headers.getSetCookie()) {
      const [pair] = raw.split(";");
      const index = pair.indexOf("=");
      jar.push({ name: pair.slice(0, index).trim(), value: pair.slice(index + 1).trim() });
    }
  };

  const started = await fetch(`${API}/api/auth/dev/login`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ email }),
  });
  collect(started);
  const challenge = await started.json();

  const verified = await fetch(`${API}/api/auth/login/verify`, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      cookie: jar.map((c) => `${c.name}=${c.value}`).join("; "),
    },
    body: JSON.stringify({
      challengeId: challenge.data.challengeId,
      code: challenge.data.code,
    }),
  });
  if (!verified.ok) throw new Error(`login failed for ${email}: ${verified.status}`);
  collect(verified);
  return jar;
}

function authorizeUrl(): string {
  const query = new URLSearchParams({
    client_id: CLIENT_ID,
    response_type: "code",
    scope: SCOPE,
    redirect_uri: REDIRECT_URI,
    state: `perf-${Date.now()}`,
  });
  return `${API}/oidc/auth?${query}`;
}

async function timeConsentScreen(context: BrowserContext): Promise<number> {
  const page = await context.newPage();
  try {
    const started = performance.now();
    await page.goto(authorizeUrl(), { waitUntil: "commit" });
    // Present *and* enabled: a disabled approve button means the screen is
    // drawn but the decision cannot yet be made, which is not interactive.
    await page.getByRole("button", { name: APPROVE }).and(page.locator("button:not([disabled])"))
      .waitFor({ state: "visible", timeout: 15_000 });
    return performance.now() - started;
  } finally {
    await page.close();
  }
}

const percentile = (sorted: number[], p: number): number =>
  sorted[Math.min(Math.max(Math.ceil((p / 100) * sorted.length) - 1, 0), sorted.length - 1)];

const median = (times: number[]): number => {
  const sorted = [...times].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;
};

function report(samples: Sample[]): string {
  const row = (sample: Sample): string => {
    const sorted = [...sample.times].sort((a, b) => a - b);
    return (
      `| ${sample.label} | ${sample.times.length} | ${median(sample.times).toFixed(0)} | ` +
      `${sorted[0].toFixed(0)} | ${sorted[sorted.length - 1].toFixed(0)} | ` +
      `${percentile(sorted, 95).toFixed(0)} |`
    );
  };
  const worst = Math.max(...samples.map((sample) => median(sample.times)));

  return [
    "# Consent screen — time to interactive",
    "",
    "<!-- Generated by persona/web/scripts/perf-consent.ts. Do not edit by hand. -->",
    "",
    "Measured in Chrome via Playwright, driving the real stack in Docker. The clock",
    "starts at `/oidc/auth`, where a person's click on Connect with Persona starts,",
    "and stops when the approve button is visible **and enabled** — the moment the",
    "decision can be made. It therefore includes the authorize redirect, the",
    "interaction lookup, the vault read and the render, not just page load.",
    "",
    `${RUNS} runs per vault, fresh page each time so nothing is cached in the tab.`,
    "",
    "| Vault | Runs | median | fastest | slowest | p95 |",
    "|---|---|---|---|---|---|",
    ...samples.map(row),
    "",
    "All figures in milliseconds.",
    "",
    `Threshold was pre-registered at **under 2 s**. Result: ` +
      `**${worst < 2000 ? "met" : "NOT met"}** (slowest median ${worst.toFixed(0)} ms).`,
    "",
  ].join("\n");
}

async function main(): Promise<void> {
  // Uses the installed Chrome rather than downloading a browser.
  const browser = await chromium.launch({ channel: "chrome" });
  const samples: Sample[] = [];

  try {
    for (const subject of SUBJECTS) {
      const context = await browser.newContext({ viewport: { width: 1492, height: 812 } });
      const cookies = (await sessionCookies(subject.email)).map((cookie) => ({
        ...cookie,
        domain: "localhost",
        path: "/",
      }));
      await context.addCookies(cookies);

      const times: number[] = [];
      // One discarded warm-up: the first hit compiles the route in dev mode and
      // would otherwise dominate the median.
      await timeConsentScreen(context);
      for (let run = 0; run < RUNS; run += 1) {
        times.push(await timeConsentScreen(context));
      }
      console.log(`${subject.label}: median ${median(times).toFixed(0)} ms`);
      samples.push({ ...subject, times });
      await context.close();
    }
  } finally {
    await browser.close();
  }

  const out = resolve(import.meta.dirname, "../../../references/performance-consent.md");
  const text = report(samples);
  writeFileSync(out, text);
  console.log(`\n${text}\nwritten to ${out}`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
