// Runs the acceptance suite and writes its result as a markdown table.
//
// The point is that the report's requirement-to-evidence table is generated from
// a real run, so it cannot quietly disagree with the code. Re-run it whenever the
// suite changes; never edit references/acceptance.md by hand.
//
// Usage: npx tsx scripts/acceptance-table.ts
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

interface JestAssertion {
  ancestorTitles: string[];
  title: string;
  status: 'passed' | 'failed' | 'pending' | 'todo' | 'skipped' | 'disabled' | 'focused';
  failureMessages: string[];
}

interface JestResult {
  success: boolean;
  numTotalTests: number;
  numPassedTests: number;
  numFailedTests: number;
  testResults: Array<{ assertionResults: JestAssertion[] }>;
}

// Run it through `npm run acceptance`, which puts the cwd at the package root.
const ROOT = process.cwd();
const OUTPUT = resolve(ROOT, '../references/acceptance.md');

const MARK: Record<string, string> = {
  passed: '✅ pass',
  failed: '❌ **fail**',
};

function runSuite(): JestResult {
  const dir = mkdtempSync(join(tmpdir(), 'persona-acceptance-'));
  const jsonPath = join(dir, 'result.json');

  try {
    execFileSync(
      'npx',
      [
        'jest',
        '--config',
        'jest.int.config.js',
        'tests/acceptance.int.test.ts',
        '--json',
        '--outputFile',
        jsonPath,
      ],
      {
        cwd: ROOT,
        env: { ...process.env, NODE_OPTIONS: '--experimental-vm-modules' },
        stdio: 'inherit',
      },
    );
  } catch {
    // A failing suite still writes the report; that is the interesting case.
  }

  try {
    return JSON.parse(readFileSync(jsonPath, 'utf8')) as JestResult;
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

function toMarkdown(result: JestResult): string {
  const assertions = result.testResults.flatMap((file) => file.assertionResults);

  const groups = new Map<string, JestAssertion[]>();
  for (const assertion of assertions) {
    // ancestorTitles[0] is the outer describe ("Persona acceptance"); the second
    // level is the requirement group.
    const group = assertion.ancestorTitles.slice(1).join(' › ') || 'General';
    groups.set(group, [...(groups.get(group) ?? []), assertion]);
  }

  const lines: string[] = [
    '# Acceptance checklist',
    '',
    '<!-- Generated by persona/scripts/acceptance-table.ts. Do not edit by hand. -->',
    '',
    'Each row is a claim the project makes, and the test that proves it. Produced by',
    'running `persona/tests/acceptance.int.test.ts` against a real PostgreSQL database',
    'and a real OpenID Connect authorization-code flow — not a simulation.',
    '',
    `**${result.numPassedTests} of ${result.numTotalTests} passing.**`,
    '',
  ];

  for (const [group, rows] of groups) {
    lines.push(`## ${group}`, '', '| Requirement | Result |', '|---|---|');
    for (const row of rows) {
      lines.push(`| ${row.title.replace(/\|/g, '\\|')} | ${MARK[row.status] ?? row.status} |`);
    }
    lines.push('');
  }

  const failures = assertions.filter((a) => a.status === 'failed');
  if (failures.length > 0) {
    lines.push('## Failures', '');
    for (const failure of failures) {
      lines.push(`### ${failure.title}`, '', '```', failure.failureMessages.join('\n').trim(), '```', '');
    }
  }

  return lines.join('\n');
}

const result = runSuite();
writeFileSync(OUTPUT, toMarkdown(result));
console.log(`\nWrote ${OUTPUT} — ${result.numPassedTests}/${result.numTotalTests} passing.`);
process.exit(result.numFailedTests > 0 ? 1 : 0);
