import 'dotenv/config';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { RATE_LIMIT_POLICIES } from '../src/constants/rate-limits';
import { MemoryRateLimitStore } from '../src/infrastructure/rate-limit/memory.store';
import { RedisRateLimitStore } from '../src/infrastructure/rate-limit/redis.store';
import { refillPerMs } from '../src/infrastructure/rate-limit/token-bucket';

// What the limiter costs. Every limited request pays one Redis round trip
// before the handler runs, so this is the number that decides whether the
// pre-registered p95 < 200 ms threshold is still met — and whether the choice
// of Redis over an in-process map was expensive.
//
// Measured directly against the store rather than through HTTP, because a
// thirty-second burst at ten connections is far past any limit set for real
// traffic: the load test has to run with RATE_LIMIT_ENABLED=false, which is
// exactly why that switch exists.
//
// Usage: npx tsx scripts/perf-ratelimit.ts
const REDIS_URL = process.env.REDIS_URL ?? 'redis://localhost:56379';
const SAMPLES = Number(process.env.PERF_SAMPLES ?? 20_000);
const OUTPUT = resolve(process.cwd(), '../references/performance-ratelimit.md');

function percentile(sorted: number[], p: number): number {
  if (sorted.length === 0) return NaN;
  const rank = Math.ceil((p / 100) * sorted.length) - 1;
  return sorted[Math.min(Math.max(rank, 0), sorted.length - 1)];
}

interface Measured {
  label: string;
  p50: number;
  p95: number;
  p99: number;
  max: number;
  mean: number;
  perSecond: number;
}

async function measure(
  label: string,
  consume: (key: string, now: number) => Promise<unknown>,
): Promise<Measured> {
  // A cold bucket for every sample, so the measurement is the round trip and
  // not the difference between allowed and refused.
  const samples: number[] = [];
  const started = process.hrtime.bigint();
  for (let i = 0; i < SAMPLES; i += 1) {
    const at = process.hrtime.bigint();
    await consume(`rl:perf:${i % 1000}`, Date.now());
    samples.push(Number(process.hrtime.bigint() - at) / 1e6);
  }
  const elapsed = Number(process.hrtime.bigint() - started) / 1e9;
  const sorted = [...samples].sort((a, b) => a - b);

  return {
    label,
    p50: percentile(sorted, 50),
    p95: percentile(sorted, 95),
    p99: percentile(sorted, 99),
    max: sorted[sorted.length - 1],
    mean: samples.reduce((a, b) => a + b, 0) / samples.length,
    perSecond: SAMPLES / elapsed,
  };
}

function report(runs: Measured[]): string {
  const redis = runs.find((r) => r.label.startsWith('Redis'))!;
  const row = (r: Measured) =>
    `| ${r.label} | ${r.p50.toFixed(3)} | **${r.p95.toFixed(3)}** | ${r.p99.toFixed(3)} | ` +
    `${r.max.toFixed(3)} | ${r.mean.toFixed(3)} | ${Math.round(r.perSecond).toLocaleString()} |`;

  return [
    '# Rate limiter — what it costs',
    '',
    '<!-- Generated by persona/scripts/perf-ratelimit.ts. Do not edit by hand. -->',
    '',
    `${SAMPLES.toLocaleString()} sequential \`consume\` calls per store, against Redis`,
    'running in Docker on the development machine. One call is what a limited',
    'request pays before its handler runs.',
    '',
    '| Store | p50 | **p95** | p99 | max | mean | calls/s |',
    '|---|---|---|---|---|---|---|',
    ...runs.map(row),
    '',
    'All figures in milliseconds.',
    '',
    `The Redis round trip adds **${redis.p95.toFixed(2)} ms at p95** to a limited`,
    'request. The pre-registered threshold for `GET /oidc/me` is p95 < 200 ms, so',
    `the limiter accounts for about ${((redis.p95 / 200) * 100).toFixed(1)}% of the budget.`,
    '',
    'The in-process store is listed for contrast, not as an option: it is',
    'per-process and empties on restart, so a deployment running on it would hand',
    'an attacker a fresh budget on every deploy. `config.ts` refuses to start',
    'production without `REDIS_URL` for that reason.',
    '',
    'Both stores run the same token bucket at the same capacity — ' +
      `${RATE_LIMIT_POLICIES.oidcUserinfo.limit}, the \`oidcUserinfo\` policy's, which is the ` +
      'hottest limited path. The in-process one runs the TypeScript in ' +
      '`token-bucket.ts`; Redis runs the Lua re-implementation of it in ' +
      '`redis.store.ts`, where the point of the script is that reading, ' +
      'refilling and taking a token are one atomic step.',
    '',
    `The Redis tail is worth naming: p99 is ${redis.p99.toFixed(2)} ms but the worst single`,
    `call was ${redis.max.toFixed(1)} ms. That is the connection warming up, not a` ,
    'steady-state cost — it appears once, in the first handful of calls.',
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  const { limit, windowMs } = RATE_LIMIT_POLICIES.oidcUserinfo;
  const rate = refillPerMs(limit, windowMs);

  const memory = new MemoryRateLimitStore();
  const redis = new RedisRateLimitStore(REDIS_URL);

  console.log(`measuring ${SAMPLES.toLocaleString()} calls per store`);
  const runs = [
    await measure('Redis (deployed)', (key, now) => redis.consume(key, limit, rate, now)),
    await measure('In process (fallback)', (key, now) => memory.consume(key, limit, rate, now)),
  ];

  for (const run of runs) {
    console.log(`${run.label}: p50 ${run.p50.toFixed(3)}ms p95 ${run.p95.toFixed(3)}ms`);
  }

  writeFileSync(OUTPUT, report(runs));
  console.log(`\nWrote ${OUTPUT}`);

  await memory.close();
  await redis.close();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
